name: build

on:
  push:
    branches:
      - master
    tags:
    paths:
      - ".github/workflows/ci-build.yml"
      - "Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/ci-build.yml"
      - "Dockerfile"

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: build jsonresume image without pushing (only outside master)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          docker buildx build \
              --platform linux/amd64 .

      - name: build jsonresume image for ghcr.io and DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          USERNAME: ${{ github.actor }}
        run: |
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          echo ${DOCKER_HUB_TOKEN} | docker login -u paskal --password-stdin
          docker buildx build --push \
              --platform linux/amd64,linux/arm64 \
              -t ghcr.io/paskal/jsonresume:latest -t paskal/jsonresume:latest .

      - name: remote push to terrty.net/cv/ from master after image update
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl https://hooks.terrty.net/update/terrty-cv/${UPDATER_KEY}
